login=com.LoginAction
logout=com.LogoutAction
shop1=com.Shop1Action
shop2=com.Shop2Action
ShoppingStarted=com.WelcomeAction
shopping.start=shop1.jsp
shopping=com.ShoppingAction
shop1=shop2.jsp
shop2=invoice.jsp
invoice=com.InvoiceAction
login.success=welcome.jsp
login.register=register.jsp
login.alreadylogin=loginWarn.jsp
register=com.RegisterAction
register.success=login.jsp
logout.success=login.jsp
index=com.IndexAction
index.EnterShop=login.jsp
loginFromregister=com.LoginFromregisterAction
registerFromlogin=com.RegisterFromloginAction
error.somethingWrong=error.jsp